const cityData = [
  { city: '', district: '', state: '' },
    { city: 'Mumbai', district: 'Mumbai', state: 'Maharashtra' },
    { city: 'Delhi', district: 'Delhi', state: 'Delhi' },
    { city: 'Bengaluru', district: 'Bengaluru', state: 'Karnataka' },
    { city: 'Chennai', district: 'Chennai', state: 'Tamil Nadu' },
    { city: 'Kolkata', district: 'Kolkata', state: 'West Bengal' },
    { city: 'Hyderabad', district: 'Hyderabad', state: 'Telangana' },
    { city: 'Ahmedabad', district: 'Ahmedabad', state: 'Gujarat' },
    { city: 'Pune', district: 'Pune', state: 'Maharashtra' },
    { city: 'Jaipur', district: 'Jaipur', state: 'Rajasthan' },
    { city: 'Lucknow', district: 'Lucknow', state: 'Uttar Pradesh' },
    { city: 'Kanpur', district: 'Kanpur', state: 'Uttar Pradesh' },
    { city: 'Nagpur', district: 'Nagpur', state: 'Maharashtra' },
    { city: 'Patna', district: 'Patna', state: 'Bihar' },
    { city: 'Indore', district: 'Indore', state: 'Madhya Pradesh' },
    { city: 'Thane', district: 'Thane', state: 'Maharashtra' },
    { city: 'Bhopal', district: 'Bhopal', state: 'Madhya Pradesh' },
    { city: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh' },
    { city: 'Vadodara', district: 'Vadodara', state: 'Gujarat' },
    { city: 'Surat', district: 'Surat', state: 'Gujarat' },
    { city: 'Ludhiana', district: 'Ludhiana', state: 'Punjab' },
    { city: 'Agra', district: 'Agra', state: 'Uttar Pradesh' },
    { city: 'Nashik', district: 'Nashik', state: 'Maharashtra' },
    { city: 'Faridabad', district: 'Faridabad', state: 'Haryana' },
    { city: 'Meerut', district: 'Meerut', state: 'Uttar Pradesh' },
    { city: 'Rajkot', district: 'Rajkot', state: 'Gujarat' },
    { city: 'Varanasi', district: 'Varanasi', state: 'Uttar Pradesh' },
    { city: 'Srinagar', district: 'Srinagar', state: 'Jammu and Kashmir' },
    { city: 'Amritsar', district: 'Amritsar', state: 'Punjab' },
    { city: 'Allahabad', district: 'Allahabad', state: 'Uttar Pradesh' },
    { city: 'Howrah', district: 'Howrah', state: 'West Bengal' },
    { city: 'Coimbatore', district: 'Coimbatore', state: 'Tamil Nadu' },
    { city: 'Vijayawada', district: 'Vijayawada', state: 'Andhra Pradesh' },
    { city: 'Jodhpur', district: 'Jodhpur', state: 'Rajasthan' },
    { city: 'Madurai', district: 'Madurai', state: 'Tamil Nadu' },
    { city: 'Raipur', district: 'Raipur', state: 'Chhattisgarh' },
    { city: 'Kota', district: 'Kota', state: 'Rajasthan' },
    { city: 'Guwahati', district: 'Guwahati', state: 'Assam' },
    { city: 'Chandigarh', district: 'Chandigarh', state: 'Chandigarh' },
    { city: 'Solapur', district: 'Solapur', state: 'Maharashtra' },
    { city: 'Hubballi-Dharwad', district: 'Hubballi-Dharwad', state: 'Karnataka' },
    { city: 'Bareilly', district: 'Bareilly', state: 'Uttar Pradesh' },
    { city: 'Moradabad', district: 'Moradabad', state: 'Uttar Pradesh' },
    { city: 'Mysuru', district: 'Mysuru', state: 'Karnataka' },
    { city: 'Gurgaon', district: 'Gurgaon', state: 'Haryana' },
    { city: 'Aligarh', district: 'Aligarh', state: 'Uttar Pradesh' },
    { city: 'Jalandhar', district: 'Jalandhar', state: 'Punjab' },
    { city: 'Tiruchirappalli', district: 'Tiruchirappalli', state: 'Tamil Nadu' },
    { city: 'Bhubaneswar', district: 'Bhubaneswar', state: 'Odisha' },
    { city: 'Salem', district: 'Salem', state: 'Tamil Nadu' },
    { city: 'Warangal', district: 'Warangal', state: 'Telangana' },
    { city: 'Guntur', district: 'Guntur', state: 'Andhra Pradesh' },
    { city: 'Bhiwandi', district: 'Bhiwandi', state: 'Maharashtra' },
    { city: 'Saharanpur', district: 'Saharanpur', state: 'Uttar Pradesh' },
    { city: 'Gorakhpur', district: 'Gorakhpur', state: 'Uttar Pradesh' },
    { city: 'Bikaner', district: 'Bikaner', state: 'Rajasthan' },
    { city: 'Amravati', district: 'Amravati', state: 'Maharashtra' },
    { city: 'Noida', district: 'Noida', state: 'Uttar Pradesh' },
    { city: 'Jamshedpur', district: 'Jamshedpur', state: 'Jharkhand' },
    { city: 'Bhilai', district: 'Bhilai', state: 'Chhattisgarh' },
    { city: 'Cuttack', district: 'Cuttack', state: 'Odisha' },
    { city: 'Firozabad', district: 'Firozabad', state: 'Uttar Pradesh' }
  ];
  const site=[
   
  ]
  
  export default cityData;
  