import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Shopify",
    description: "Generated by create next app",
    icons: {
        icon: "/asserts/logo/logo.svg",
    },
};
