import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextContent from "../../contextapi";
import AuthProvider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/asserts/logo/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<
  {
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <ContextContent>
          <AuthProvider>
            {children}
          </AuthProvider>
        </ContextContent>
      </body>
    </html>
  );
}
