import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextContent from "../../contextapi";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopify",
  description: "Generated by ULNLABS Team",
  icons: {
    icon: "/asserts/logo/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<
{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <ContextContent>
       

        {children}
        </ContextContent>
        </body>
    </html>
  );
}
