import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextContent from "../../contextapi";
import AuthProvider from "./Provider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopify",
  description: "Generated by ULNLABS Team",
  icons: {
    icon: "/asserts/logo/logo.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<
  {
    children: React.ReactNode;
  }>) {
  return (
    <html lang="en" className="">
   <head>
       <meta name="google-site-verification"             content="uCn8oX5ny3yGjcw1zMVCSqCF6grMcETD6A3Ok034c84" />
    </head>
      <body className={inter.className}>
        <ContextContent>
          <AuthProvider>
              {children}
          </AuthProvider>
        </ContextContent>
      </body>
    </html>
  );
}
