import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "@/app/components/navigation/SideBar";
import Header from "@/app/components/navigation/Header";
import { UserProvider } from "@/UserContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/asserts/logo/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <UserProvider>
    
    <div className="min-h-screen max-w-screen flex justify-between">
      <SideBar />
      <div className="w-full max-h-screen overflow-hidden">
        <Header />
        <div className="w-full max-h-[calc(100vh_-_60px)] overflow-y-scroll flex flex-col  justify-start scrollbar-hide">
          {children}
        </div>
      </div>
    </div>
  </UserProvider>    
  );
}
