import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SideBar from "../components/navigation/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/asserts/logo/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div className="min-h-screen w-screen flex justify-between">
        <SideBar/>
        {children}
      </div>
  );
}
